### Задание 1.
- 1. Скачать данные по ссылке
https://www.kaggle.com/datasets/ionaskel/laptop-prices
- 2. Считать данные с помощью pandas
- 3. Вывести на экран первые 5 строк

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("laptop_price.csv", sep=',' , encoding='windows-1251')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

- 1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [89]:
df['Cpu_Company'] = df['Cpu'].apply(lambda x : x.split(" ")[0])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_Amount,Memory_Type,SSD,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8.0,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,128.0,SSD,1,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8.0,Intel HD Graphics 6000,macOS,1.34,898.94,128.0,Flash,0,Intel
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8.0,Intel HD Graphics 620,No OS,1.86,575.00,256.0,SSD,1,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16.0,AMD Radeon Pro 455,macOS,1.83,2537.45,512.0,SSD,1,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8.0,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,256.0,SSD,1,Intel

- 1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [ ]:
def memory(memory_str):
    gb = memory_str.split(" ")[0]
    if gb.endswith('GB'):
        gb = float(gb[:-2])
    elif gb.endswith('TB'):
        gb = float(gb[:-2]) * 1024
    return gb

df['Memory_Amount'] = df['Memory'].apply(memory)
df.head()

- 1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [ ]:
df['Memory_Type'] = df['Memory'].apply(lambda x : x.split(" ")[1])
df.head()

- 1.4 Удалите признаки Memory и ScreenResolution

In [39]:
# df.drop(columns= 'Memory', inplace=True)
# df.head()
df.drop(columns= 'ScreenResolution' , inplace=True)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,128.0,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,128.0,Flash
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,256.0,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,512.0,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,256.0,SSD

### Задание 2.
- 2.1 Создайте признак SSD, который изначально равен 0

In [40]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,128.0,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,128.0,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,256.0,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,512.0,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,256.0,SSD,0

- 2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [135]:
df.loc[df['Memory_Type'] == 'SSD', 'SSD'] = 1
df.head()
# df.drop(columns = 'target', inplace=True)
# df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_Amount,Memory_Type,SSD,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8.0,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,128.0,SSD,1,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8.0,Intel HD Graphics 6000,macOS,1.34,898.94,128.0,Flash,0,Intel
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8.0,Intel HD Graphics 620,No OS,1.86,575.00,256.0,SSD,1,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16.0,AMD Radeon Pro 455,macOS,1.83,2537.45,512.0,SSD,1,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8.0,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,256.0,SSD,1,Intel

- 2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [ ]:
# def memory(memory_str):
#     kg = memory_str.split(" ")[0]
#     if kg.endswith('kg'):
#         kg = float(kg[:-2])
#     return kg

# df['Weight'] = df['Weight'].apply(memory)
# df.head()

df['Ram'] = df['Ram'].str.replace('GB','').astype ('float')
df.head()

### Задание 3.
- Создайте датафрейм с клиентами: laptop_id - это индексы датафрейма с ноутбуками

In [61]:
clients = pd.DataFrame({
 'client_id': [45, 32, 67, 33, 43],
 'laptop_id': [506, 398, 710, 120, 1999]
})
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

- 3.1 Присоедините к таблице clients данные по ноутбукам через метод join

In [ ]:
clients_id = clients.set_index('laptop_id')
clients_id
df_id = df.set_index('laptop_ID')
df_id.head()

In [ ]:
results_join = clients_id.join(df_id).head()
results_join

- 3.2 Присоедините к таблице clients данные по ноутбукам через метод merge

In [ ]:
merged_left = clients.merge(df, left_on='laptop_id', right_on= 'laptop_ID')
merged_left

### Задание 4. Составьте несколько сводных таблиц
- 4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя. Отсортируйте от меньшей стоимости к большей

In [ ]:
df.groupby('Company').agg({'Price_euros' : 'mean'}).sort_values('Price_euros')
# pd.crosstab(index=df['Company'], columns=df['Price_euros']).aggfunc= 'mean'

- 4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [ ]:
df.groupby('Cpu_Company').agg({'Price_euros' : ['min', 'mean', 'max']})

- 4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [111]:
pd.crosstab(index=df['Cpu_Company'], columns=df['Ram'], values= df['Product'], aggfunc='count')

Ram          2.0    4.0   6.0    8.0   12.0   16.0  24.0  32.0  64.0
Cpu_Company
AMD           1.0   31.0  13.0   12.0   2.0    3.0   NaN   NaN   NaN
Intel        21.0  343.0  28.0  607.0  23.0  197.0   3.0  17.0   1.0
Samsung       NaN    1.0   NaN    NaN   NaN    NaN   NaN   NaN   NaN

- 4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [ ]:
df.pivot_table(index='OpSys',
               columns='Ram',
               values='Price_euros',
               aggfunc='mean',
               fill_value= '-')

### Задание 5*.
- 5.1 Ноутбуков каких компаний и с каким процессором больше?

In [130]:
pd.crosstab(index=df['Cpu_Company'],
            columns=df['Company'])

Company,Acer,Apple,Asus,Chuwi,Dell,Fujitsu,Google,HP,Huawei,LG,Lenovo,MSI,Mediacom,Microsoft,Razer,Samsung,Toshiba,Vero,Xiaomi
Cpu_Company,,,,,,,,,,,,,,,,,,,
AMD,10,0,11,0,0,0,0,25,0,0,16,0,0,0,0,0,0,0,0
Intel,93,21,147,3,297,3,3,249,2,3,281,54,7,6,7,8,48,4,4
Samsung,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

- 5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [133]:
pd.crosstab(index=df['Memory_Type'],
            columns=df['Memory_Amount'])

Memory_Amount,8.0,16.0,32.0,64.0,128.0,180.0,240.0,256.0,500.0,508.0,512.0,1024.0,2048.0
Memory_Type,,,,,,,,,,,,,
Flash,0,7,38,16,4,0,0,8,0,0,2,0,0
HDD,0,0,1,0,1,0,0,0,132,0,0,225,16
Hybrid,0,0,0,0,0,0,0,0,0,1,0,9,0
SSD,1,3,6,1,172,5,1,500,0,0,138,16,0